# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ode <- function(f, y, ts, rtol, atol) {
    .Call('_lsoda_ode', PACKAGE = 'lsoda', f, y, ts, rtol, atol)
}

