# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ordinary differential equation solver using lsoda
#' @param f R function with signature function(t,y)
#' @param y vector of initial state values
#' @param times vector of times -- including the start time
#' @param rtol double for the relative tolerance
#' @param atol double for the absolute tolerance
#' @return a matrix for times in the first column and the state values in the other columns. 
#' @export
ode <- function(y, times, func, rtol = 1e-6, atol = 1e-6) {
    .Call('_lsoda_ode', PACKAGE = 'lsoda', y, times, func, rtol, atol)
}

